/* eslint-disable */
// @ts-nocheck
// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes
import { Route as rootRoute } from './routes/__root'
import { Route as AdminRoute } from './routes/admin'
import { Route as SuccessRoute } from './routes/success'
import { Route as IndexRoute } from './routes/index'

// Create/Update Routes
const AdminRouteRoute = AdminRoute.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRoute,
} as any)

const SuccessRouteRoute = SuccessRoute.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => rootRoute,
} as any)

const IndexRouteRoute = IndexRoute.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface
declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteRoute
      parentRoute: typeof rootRoute
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRoute
      parentRoute: typeof rootRoute
    }
    '/success': {
      id: '/success'
      path: '/success'
      fullPath: '/success'
      preLoaderRoute: typeof SuccessRouteRoute
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree
export interface FileRoutesByFullPath {
  '/': typeof IndexRouteRoute
  '/admin': typeof AdminRouteRoute
  '/success': typeof SuccessRouteRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRouteRoute
  '/admin': typeof AdminRouteRoute
  '/success': typeof SuccessRouteRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRouteRoute
  '/admin': typeof AdminRouteRoute
  '/success': typeof SuccessRouteRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/admin' | '/success'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/admin' | '/success'
  id: '__root__' | '/' | '/admin' | '/success'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRouteRoute
  AdminRoute: typeof AdminRouteRoute
  SuccessRoute: typeof SuccessRouteRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRouteRoute,
  AdminRoute: AdminRouteRoute,
  SuccessRoute: SuccessRouteRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
